name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/documentation.yml
      - Sources/Echo/**.swift

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Gen Documentation
        uses: SwiftDocOrg/swift-doc@master
        with:
          inputs: "Sources/Echo"
          module-name: Echo
          output: "Documentation"
      - name: Upload
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "Documentation"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
